/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school.managment.system;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Sithumini
 */
public class login extends javax.swing.JFrame {

   Connection con=null;
   Statement stmt=null;
    public login() {
        initComponents();
        con= DBconnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogin = new javax.swing.JLabel();
        lblUN = new javax.swing.JLabel();
        lblPW = new javax.swing.JLabel();
        txtUN = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        txtPW = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogin.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(102, 255, 102));
        lblLogin.setText("LOGIN");
        getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 150, -1));

        lblUN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblUN.setForeground(new java.awt.Color(255, 102, 255));
        lblUN.setText("User Name");
        getContentPane().add(lblUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 210, 150, -1));

        lblPW.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPW.setForeground(new java.awt.Color(255, 102, 255));
        lblPW.setText("passward");
        getContentPane().add(lblPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 280, 140, -1));

        txtUN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 140, -1));

        btnLogin.setBackground(new java.awt.Color(0, 0, 255));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogin.setText("Log in");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 110, 40));

        txtPW.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPW.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(txtPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/managment/system/1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
      try{
        stmt=con.createStatement();
          String query="select *from admin";
         String username=txtUN.getText();
         String passward=txtPW.getText();
         ResultSet rs =stmt.executeQuery(query);
         while(rs.next())
         {
             if(username.equals(rs.getString(2)) && passward.equals(rs.getString(3)))
             {
                 
                 setVisible(false);
                 Home view=new Home();
              view. setVisible(true);
            
             
             }
               else{
                 JOptionPane.showMessageDialog(null,"please enter correct user name && passward");
             }
           
             
             
         }
             
         }
      catch(Exception e)
      {
          System.out.println(e);
      }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPW;
    private javax.swing.JLabel lblUN;
    private javax.swing.JPasswordField txtPW;
    private javax.swing.JTextField txtUN;
    // End of variables declaration//GEN-END:variables
}
